### ISSUE TITLE
TMC_Rotate() does not work

### ISSUE THREAD

**Issue by rayaan92** [alambe94/STM32_TMC2130#1]
Good day,

could you please explain how the TMC_Rotate() function works ?, This is my implementation of it, but doesn't seem to do anything.

void motor_control(int32_t velocity)
{
	TMC_Rotate(&Motor_X_Controller, velocity);
    while(!(TMC_Get_Status(&Motor_X_Controller) & STATUS_STALLGUARD_ACTIVE))
	  {
	  TMC_Loop(&Motor_X_Controller);
	  }
}

**Comment by alambe94** [comment]
Hello,
tmc2130_interface_api.c and tmc2130_step_generator.c are based on TMC2130.c and StepDir.c from 
https://github.com/trinamic/TMC-API/blob/master/tmc/ic/TMC2130/TMC2130.c
https://github.com/trinamic/TMC-EvalSystem/blob/master/tmc/StepDir.c
I modified them to my to suit my coding style.
For step generation, you need a timer interrupt at 131 Khz, TMC_TIM_ISR is called from stm32f4xx_it.c.

**Comment by alambe94** [comment]
TMC_Loop() moved to separate ISR, now you don't have to call it manually.
ISR priorities TMC_Main_ISR > TMC_Loop_ISR > Systick ISR

**Comment by rayaan92** [comment]
thanks for you help, got it working.

**Comment by rayaan92** [comment]
Hello,

I have another question for you, is it possible to implement 2 stepper
motor with your driver ?

Kind regards

**Comment by alambe94** [comment]
Theoretically, you can add as many as you want but they are not synchronized.

**Comment by rayaan92** [comment]
I tried setting up a second motor, basically just copied the code for the
first motor and changed the typedef and the controller name, but it seems
to get stuck in a weird state when setting up the second motor.

you have any idea what would cause that ?

**Comment by alambe94** [comment]
Hello added the second instance, I think the issue is with compiler optimization.
Set the compiler optimization option other than 'None (-O0)'.
I would recommend 'optimize for speed (-Ofast)'.
